-- MySQL Script generated by MySQL Workbench
-- Mon Jun 29 11:56:52 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `codgo_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(60) NOT NULL,
  `cpf_cliente` VARCHAR(11) NOT NULL,
  `telefone_cliente` VARCHAR(15) NOT NULL,
  `email_cliente` VARCHAR(60) NOT NULL,
  `cep_cliente` VARCHAR(8) NOT NULL,
  `endereco_cliente` VARCHAR(50) NOT NULL,
  `data_nacimento_cliente` DATE NOT NULL,
  `sexo_cliente` ENUM("Masculino", "Feminino", "Outros") NOT NULL,
  `genero_cliente` VARCHAR(30) NULL,
  `etinia_cliente` VARCHAR(30) NOT NULL,
  `nome_social_cliente` VARCHAR(60) NULL,
  `estado_civil_cliente` VARCHAR(30) NOT NULL,
  `data_cadastro_cliente` DATE NULL,
  `clientecol` VARCHAR(45) NULL DEFAULT 'current_timestamp()',
  PRIMARY KEY (`codgo_cliente`),
  UNIQUE INDEX `cpf_cliente_UNIQUE` (`cpf_cliente` ASC) VISIBLE,
  UNIQUE INDEX `email_cliente_UNIQUE` (`email_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `codigo_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(30) NOT NULL,
  `categoria` VARCHAR(30) NOT NULL,
  `descricao_produto` TEXT NOT NULL,
  `fabricante` VARCHAR(30) NOT NULL,
  `marca` VARCHAR(30) NOT NULL,
  `preco` DECIMAL(6,2) NULL,
  PRIMARY KEY (`codigo_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `codigo_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(60) NOT NULL,
  `cpf_funcionario` VARCHAR(11) NOT NULL,
  `rg_funcionario` VARCHAR(11) NOT NULL,
  `certidao_nacimento_filho` VARCHAR(30) NULL,
  `certificado_de_reservista` VARCHAR(12) NULL,
  `certidao_de_casamento` VARCHAR(30) NULL,
  `telefone_funcionario` VARCHAR(15) NULL,
  `email_funcionario` VARCHAR(60) NOT NULL,
  `endereco_funcionario` VARCHAR(50) NOT NULL,
  `cep_funcionario` VARCHAR(8) NOT NULL,
  `data_nascimento_funcionario` DATE NOT NULL,
  `sexo_funcionario` ENUM("Masculino", "Feminino", "outros") NULL,
  `genero_funcionario` VARCHAR(30) NULL,
  `etinia_funcionario` VARCHAR(30) NOT NULL,
  `nome_social_funcionario` VARCHAR(60) NULL,
  `estado_civil_funcionario` VARCHAR(30) NOT NULL,
  `data_admissao` DATE NULL DEFAULT current_timestamp(),
  `data_demissao` DATE NULL,
  `escolariedade` VARCHAR(45) NULL,
  `escolaridade` ENUM("Fundamental", "medio", "Graduacao", "Pos-graduacao") NULL,
  `pis` VARCHAR(11) NOT NULL,
  `carteira_trabalho` VARCHAR(11) NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`codigo_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoque` (
  `codigo_estoque` INT NULL AUTO_INCREMENT,
  `codigo_produto` INT NOT NULL,
  `fabricacao` DATE NOT NULL,
  `validade` DATE NOT NULL,
  `lote` VARCHAR(30) NOT NULL,
  `data_entrada` DATE NULL DEFAULT current_timestamp(),
  `quantidade_atual` INT NOT NULL,
  `setor` VARCHAR(30) NULL,
  `estoquecol` VARCHAR(45) NOT NULL,
  INDEX `fk_estoque_Produto_idx` (`codigo_produto` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_Produto`
    FOREIGN KEY (`codigo_produto`)
    REFERENCES `mydb`.`Produto` (`codigo_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `codigo_venda` INT NULL AUTO_INCREMENT,
  `codgo_cliente` INT NOT NULL,
  `codigo_funcionario` INT NOT NULL,
  `data_hora` DATETIME NULL DEFAULT current_timestamp(),
  `total` DECIMAL(7,2) NULL,
  `vendacol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_venda`),
  INDEX `fk_venda_funcionario1_idx` (`codigo_funcionario` ASC) VISIBLE,
  INDEX `fk_venda_cliente1_idx` (`codgo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`codigo_funcionario`)
    REFERENCES `mydb`.`funcionario` (`codigo_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`codgo_cliente`)
    REFERENCES `mydb`.`cliente` (`codgo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`intens da venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`intens da venda` (
  `codigo_itens_venda` INT NULL AUTO_INCREMENT,
  `codigo_venda` INT NOT NULL,
  `codigo_produto` INT NOT NULL,
  `desconto` DECIMAL(4,2) NULL DEFAULT default0.0,
  `quantidade` INT NOT NULL DEFAULT default 1,
  `subtotal` DECIMAL(7,2) NULL,
  PRIMARY KEY (`codigo_itens_venda`),
  INDEX `fk_intens da venda_venda1_idx` (`codigo_venda` ASC) VISIBLE,
  INDEX `fk_intens da venda_Produto1_idx` (`codigo_produto` ASC) VISIBLE,
  CONSTRAINT `fk_intens da venda_venda1`
    FOREIGN KEY (`codigo_venda`)
    REFERENCES `mydb`.`venda` (`codigo_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_intens da venda_Produto1`
    FOREIGN KEY (`codigo_produto`)
    REFERENCES `mydb`.`Produto` (`codigo_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `codigo_pagamento` INT NULL AUTO_INCREMENT,
  `codigo_venda` INT NOT NULL,
  `forma_pagamento` ENUM("Pix", "Credito", "Dinheiro", "Voucher") NULL,
  `informacao_cartao` VARCHAR(255) NULL,
  `total_pagamento` DECIMAL(7,2) NOT NULL,
  `valor_recebido` DECIMAL(5,2) NOT NULL,
  `troco` DECIMAL(4,2) NULL,
  `numero_parcela` INT NOT NULL DEFAULT default 1,
  `valor_parcela` DECIMAL(7,2) NULL,
  `status_pagamento` ENUM("Pendente", "Aprovado", "Recusado") NULL DEFAULT 'default \"Pendente\"',
  PRIMARY KEY (`codigo_pagamento`),
  INDEX `fk_pagamento_venda1_idx` (`codigo_venda` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_venda1`
    FOREIGN KEY (`codigo_venda`)
    REFERENCES `mydb`.`venda` (`codigo_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
